### ISSUE TITLE
monument marker not working?

### ISSUE THREAD

**Issue by TheSoulrester** [KovuTheHusky/dynmap-structures#18]
**Describe the bug**
monument markers aren't created at the dynmap :( there are three monuments streight nearby - but no marker is available for each of them.

![Monument1](https://user-images.githubusercontent.com/7083599/59741994-d473e880-926c-11e9-9e81-15235fc952ca.PNG)
![Monument12PNG](https://user-images.githubusercontent.com/7083599/59741995-d473e880-926c-11e9-8392-febd6e05bc8e.PNG)

 - Spigot 1.14.2
 - dynmap-structures-2.2.1-SNAPSHOT.jar

here is my config:
```
structures:
  buriedtreasure: false
  desertpyramid: true
  endcity: true
  fortress: true
  igloo: true
  junglepyramid: true
  mansion: true
  mineshaft: false
  monument: true
  oceanruin: false
  pillageroutpost: true
  shipwreck: false
  stronghold: true
  swamphut: true
  village: true
layer:
  name: Strukturen
  hidebydefault: false
  layerprio: 10
  nolabels: false
  minzoom: 0
  inc-coord: false
```
