### ISSUE TITLE
Add support for multiple layers?

### ISSUE THREAD

**Issue by kharidiron** [KovuTheHusky/dynmap-structures#21]
Between the proliferation of buried treasure, ocean ruin, shipwreck, and village markers, it might be useful to have the ability to create additional layers in which one can split those off. Basically have more layers than just a 'Structures'.

Or, if this is already possible and I'm just missing it, can you please tell me how to do so / add it to the documentation?

**Comment by KovuTheHusky** [comment]
It's not possible yet. Do you have an opinion on which categories to split them into? I know dynmap-mobs splits Mobs and Vehicles into their own layers, for example.

**Comment by kharidiron** [comment]
The two I feel that would benefit the most would be villages and shipwrecks since both tend to clog the map when zoomed out the farthest. If I had to choose between the two though, I'd definitely go with giving villages their own layer. Everything else (temples, strongholds, witch huts, etc...) are all distinct enough that they don't blend together too much. These are just my opinions however; I don't really have any definitive reason to believe that these would be the best for everyone else as well.

**Comment by axipher** [comment]
It would be nice to be able to configure multiple structures layers that can be set up to display different groups of structures, maybe set up something like this in the config.yml:

```
# default visibilty states for all layers
structures:
  buriedtreasure: false
  desertpyramid: false
  endcity: false
  fortress: false
  igloo: false
  junglepyramid: false
  mansion: false
  mineshaft: false
  monument: false
  oceanruin: false
  pillageroutpost: false
  shipwreck: false
  stronghold: false
  swamphut: false
  village: false
layer1:
  name: Structures - Villages and Outpost
  hidebydefault: false
  layerprio: 10
  nolabels: false
  minzoom: 0
  inc-coord: false
  pillageroutpost: true
  village: true
layer2:
  name: Structures - Surface
  hidebydefault: false
  layerprio: 11
  nolabels: false
  minzoom: 0
  inc-coord: false
  desertpyramid: true
  igloo: true
  junglepyramid: true
  mansion: true
  monument: true
  pillageroutpost: true
  swamphut: true
  village: true
layer3:
  name: Structures - Underground
  hidebydefault: true
  layerprio: 12
  nolabels: false
  minzoom: 0
  inc-coord: false
  mineshaft: true
  stronghold: true
layer4:
  name: Structures - Underwater
  hidebydefault: true
  layerprio: 12
  nolabels: false
  minzoom: 0
  inc-coord: false
  buriedtreasure: true
  monument: true
  oceanruin: true
  shipwreck: true
```
