### ISSUE TITLE
Doesn't display on 1.14.3

### ISSUE THREAD

**Issue by Greg-J** [KovuTheHusky/dynmap-structures#23]
Installed, restarted, nothing shows although the "Structures" panel is present, toggling it does nothing.

http://mc.johnson.io

Running PaperMC-131 for MC 1.14.3

```
structures:
  buriedtreasure: false
  desertpyramid: true
  endcity: true
  fortress: true
  igloo: true
  junglepyramid: true
  mansion: true
  mineshaft: false
  monument: true
  oceanruin: false
  pillageroutpost: true
  shipwreck: false
  stronghold: true
  swamphut: true
  village: true
layer:
  name: Structures
  hidebydefault: false
  layerprio: 10
  nolabels: false
  minzoom: 0
  inc-coord: false

```
